### PR TITLE
chore: Release/1.41

### PR DESCRIPTION
**Pull request by markphelps**
This PR simply shows the diff after cherry picking the following commits for a bugfix release:

- https://github.com/flipt-io/flipt/commit/ec8f52a92a18511847ec4a5090cc601505fc1197
- https://github.com/flipt-io/flipt/commit/1c70110a85b02d4d64c8682a465f4ef8139d4fbd

These commits are already on main

### CODE REVIEW

**Comment by thepabloaguilar** [comment]
@markphelps just to let you know, I've deployed using the `main` branch version! Just waiting the token to expire which will happen in ~12h and see if we'll have any problem with that

**Comment by markphelps** [comment]
Awesome I will wait to do the release until I hear back @thepabloaguilar

**Review by erka — APPROVED** [review]
looks great!

**Review by GeorgeMac — APPROVED** [review]

**Comment by thepabloaguilar** [comment]
It's working @markphelps

**Pull request merged**
