### PR TITLE
chore: fix install.sh

### PR DESCRIPTION
**Pull request by erka**

### CODE REVIEW

**Comment by erka** [comment]
@markphelps it was probably always broken and this point I don't know that is the best way to resolve it. Fix it or drop .local/bin/flipt alternative?

**Comment by markphelps** [comment]
> @markphelps it was probably always broken and this point I don't know that is the best way to resolve it. Fix it or drop .local/bin/flipt alternative?

gah. probably fix it i would think

**Comment by markphelps** [comment]
@erka looks like this change was previously done on purpose for POSIX compliance? https://github.com/flipt-io/flipt/commit/835bda210a4be771fcab1aeabe720a7bcec97ffd#diff-043df5bdbf6639d7a77e1d44c5226fd7371e5259a1e4df3a0dd5d64c30dca44fR29

**Comment by erka** [comment]
@markphelps it doesn't work currently. Should it be 
```
  case ":$PATH:" in
  *":$HOME/.local/bin:"*)
```?

**Review by markphelps — APPROVED** [review]
👍🏻

**Pull request merged**
