### PR TITLE
ci(audit): add integration testing for audit webhooks

### PR DESCRIPTION
**Pull request by erka**
related #3284

### CODE REVIEW

**Comment by erka** [comment]
if there is any idea how I could verify the http request I would like to hear them

**Review by markphelps — APPROVED** [review]
looks great to me @erka ! thank you!!

as far as testing it, we could maybe try to mount the directory where `rxyt/gohrec` writes the requests to when running [record](https://github.com/frxyt/gohrec?tab=readme-ov-file#gohrec-record-record-requests)

although then we would have to do some shell foo to list and then cat the recorded request and inspect it to see if the `body` matched what we sent

another alternative if we write our own simple go http webhook handler that writes the data to a known file, then cat it out and compare to our request. dockerize it in the `build` directory and spin it up as a service in Dagger

or we just not compare the requests, as we have unit tests that should test for the body being marshalled correctly, and the bug this is covering come in the actual sending via HTTP which we didn't have existing tests for

wdty?

**Comment by markphelps** [comment]
Xnapper-2024-08-16-19 56 43

^heres an example of the recorded request I did running `frxyt/gohrec` locally in Docker and sending a POST request via curl. Note the seemingly random recorded filename as mentioned above

**Comment by erka** [comment]
@markphelps I just want to know the fact that requests are made and don't worry much about the content of those. But I can't list the files in `/gohrec/log` directory with dagger. 

Here is my changed test
```go
func withWebhook(fn testCaseFn) testCaseFn {
	return func(ctx context.Context, client *dagger.Client, base, flipt *dagger.Container, conf testConfig) func() error {
		return func() error {
			owntracks := client.Container().From("frxyt/gohrec").WithExposedPort(8080).
				WithMountedDirectory("/gohrec/log", client.Directory(), dagger.ContainerWithMountedDirectoryOpts{Owner: "gohrec"}).
				WithExec([]string{"record", "--listen=:8080", "--index"}, dagger.ContainerWithExecOpts{UseEntrypoint: true})
			err := fn(ctx, client, base, flipt.
				WithEnvVariable("FLIPT_AUDIT_SINKS_WEBHOOK_ENABLED", "true").
				WithEnvVariable("FLIPT_AUDIT_SINKS_WEBHOOK_URL", "http://owntracks:8080").
				WithServiceBinding("owntracks", owntracks.AsService()),
				conf,
			)()
			if err != nil {
				return err
			}
			ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
			defer cancel()
			files, err := owntracks.Directory("/gohrec/log").Entries(ctx)
			if err != nil {
				return err
			}
			if len(files) == 0 {
				return errors.New("no request records found")
			}
			return err
		}
	}
}
```

**Pull request merged**
