### PR TITLE
feat: support etag header for client-side eval

### PR DESCRIPTION
**Pull request by markphelps**
Re: https://github.com/flipt-io/flipt-client-sdks/issues/294

Support etag/if-none-match headers for client-side eval endpoint

```
~ » curl -v  http://localhost:8080/internal/v1/evaluation/snapshot/namespace/default
```

```
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080
> GET /internal/v1/evaluation/snapshot/namespace/default HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.6.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 1401
< Content-Type: application/json
< Etag: 7cfafac21953b341569a2a676205e0c0e5ff7e00
< Grpc-Metadata-Content-Type: application/grpc
< X-Content-Type-Options: nosniff
```

----

```
~ » curl -v  -H "If-None-Match: 7cfafac21953b341569a2a676205e0c0e5ff7e00" http://localhost:8080/internal/v1/evaluation/snapshot/namespace/default
```

```
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080
> GET /internal/v1/evaluation/snapshot/namespace/default HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.6.0
> Accept: */*
> If-None-Match: 7cfafac21953b341569a2a676205e0c0e5ff7e00
> 
< HTTP/1.1 304 Not Modified
```

### CODE REVIEW

**Comment by erka** [comment]
@markphelps your code looks great but there is a problem. If you have the namespace with some amount of flags and segments `http://localhost:8080/internal/v1/evaluation/snapshot/namespace/default` will produce different `etag`.  I believe the logic uses `map` somewhere and it produce the different order of elements in the json.

**Comment by markphelps** [comment]
> @markphelps your code looks great but there is a problem. If you have the namespace with some amount of flags and segments `http://localhost:8080/internal/v1/evaluation/snapshot/namespace/default` will produce different `etag`. I believe the logic uses `map` somewhere and it produce the different order of elements in the json.
> 
> Here is the sample
> 
> ```shell
> > curl -v http://localhost:8080/internal/v1/evaluation/snapshot/namespace/default 
> * Request completely sent off
> < HTTP/1.1 200 OK
> < Content-Length: 7011
> < Content-Type: application/json
> < Etag: 4bbaa020a72c5bd21b224bcdd11c5bf4c7c0cda3
> 
> > curl -v http://localhost:8080/internal/v1/evaluation/snapshot/namespace/default 
> * Request completely sent off
> < HTTP/1.1 200 OK
> < Content-Length: 7011
> < Content-Type: application/json
> < Etag: 92e8e67b990930eca494f3feb4536c68725dc2bf
> ```

gah you are right. good find @erka . back to the drawing board it seems

**Comment by markphelps** [comment]
> > @markphelps your code looks great but there is a problem. If you have the namespace with some amount of flags and segments `http://localhost:8080/internal/v1/evaluation/snapshot/namespace/default` will produce different `etag`. I believe the logic uses `map` somewhere and it produce the different order of elements in the json.
> > Here is the sample
> > ```shell
> > > curl -v http://localhost:8080/internal/v1/evaluation/snapshot/namespace/default 
> > * Request completely sent off
> > < HTTP/1.1 200 OK
> > < Content-Length: 7011
> > < Content-Type: application/json
> > < Etag: 4bbaa020a72c5bd21b224bcdd11c5bf4c7c0cda3
> > 
> > > curl -v http://localhost:8080/internal/v1/evaluation/snapshot/namespace/default 
> > * Request completely sent off
> > < HTTP/1.1 200 OK
> > < Content-Length: 7011
> > < Content-Type: application/json
> > < Etag: 92e8e67b990930eca494f3feb4536c68725dc2bf
> > ```
> 
> gah you are right. good find @erka . back to the drawing board it seems

Its likely related to us using `protojson` to marshal the output which does not support determinism: https://protobuf.dev/reference/go/faq/#unstable-json

we need to think of otherways we can produce a stable etag value

**Comment by markphelps** [comment]
closing for another approach

**Pull request closed without merging**
