### PR TITLE
fix(storage): map protobuf enums to ints in sql

### PR DESCRIPTION
**Pull request by lzakharov**
Hi! Previously, I've added #3436 with enabling simple protocol to support work with PgBouncer. Unfortunately, this was not a complete fix. It turned out that the SQL queries still needed to be fixed to avoid the following errors:
```
Error: creating flag: ERROR: invalid input syntax for type integer: "VARIANT_FLAG_TYPE" (SQLSTATE 22P02)
```

### CODE REVIEW

**Review by GeorgeMac — APPROVED** [review]
Nice. Thank you! I take it our other drivers have not been relying on the String() methds on these enum types, which is good.

**Comment by lzakharov** [comment]
Also, it would be nice to run Postgres integration tests with `FLIPT_DB_PREPARED_STATEMENTS_ENABLED` set to `false`. Something like this:

```go
func withPostgresSimpleProtocol(fn testCaseFn) testCaseFn {
	return func(ctx context.Context, client *dagger.Client, base, flipt *dagger.Container, conf testConfig) func() error {
		return fn(ctx, client, base, flipt.
			WithEnvVariable("FLIPT_DB_URL", "postgres://postgres:password@postgres:5432?sslmode=disable").
			WithEnvVariable("FLIPT_DB_PREPARED_STATEMENTS_ENABLED", "false").
			WithServiceBinding("postgres", client.Container().
				From("postgres:alpine").
				WithEnvVariable("POSTGRES_PASSWORD", "password").
				WithExposedPort(5432).
				WithEnvVariable("UNIQUE", uuid.New().String()).
				AsService()),
			conf,
		)
	}
}
```

What do you think?

**Comment by GeorgeMac** [comment]
@lzakharov That sounds sensible to me. Perhaps we can get both cases into the same workflow / integration cases.
Mostly, to leverage that warm cache and save on adding more integration pipelines to CI.
WDYT?

**Comment by lzakharov** [comment]
Yes, probably, it's possible to add this cases into the existing `api/postgres` workflow. Unfortunately, I'm not sure if I'll be able to figure out how to do this anytime soon. I can create a separate issue for this if you wish.

**Comment by GeorgeMac** [comment]
That's no worries @lzakharov !
Feel free to add another like you suggested and we can merge them if it becomes too costly.

**Pull request merged**
