### PR TITLE
fix(evaluation): return default value for flag with no rule/segment match

### PR DESCRIPTION
**Pull request by erka**
related #3311

### CODE REVIEW

**Review by GeorgeMac — APPROVED** [review]
Nice catch!

We should probably look into doing another patch release this AM to fix this and the other eval related fix you got in end of last week.

**Comment by erka** [comment]
> We should probably look into doing another patch release this AM to fix this and the other eval related fix you got in end of last week.

Default variant hasn't been released yet so it shouldn't be included into the patch.

**Comment by GeorgeMac** [comment]
Ah I see, thanks @erka 👍

**Comment by markphelps** [comment]
Thanks @erka ! Im guessing we need to fix this in the client side evaluation logic too?

**Pull request merged**
