### PR TITLE
fix: update attachment messaging and size to allow 1mb

### PR DESCRIPTION
**Pull request by MMartyn**
Fixes: https://github.com/flipt-io/flipt/issues/3594

### CODE REVIEW

**Comment by erka** [comment]
Hey Matt. 

Thank you for your first contribution!

**Review by markphelps — APPROVED** [review]
ty! ill add the limit to our docs as well

**Comment by markphelps** [comment]
Thank you @MMartyn !!

@all-contributors please add @MMartyn for code

**Comment by MMartyn** [comment]
Thanks all 👍

**Pull request merged**
