### PR TITLE
Fix IsNotOneOf operator

### PR DESCRIPTION
**Pull request by proxeter**
IsNotOneOf operator used same logic as IsOneOf

### CODE REVIEW

**Review by markphelps — APPROVED** [review]
oof that is !! embarrassing.

good find @proxeter ! will put out a bug fix release tomorrow

**Comment by markphelps** [comment]
@all-contributors please add @proxeter for code

**Comment by erka** [comment]
One more place should be fixed as well
https://github.com/flipt-io/flipt/blob/504f8e0fbbff884c06ce1edbdfdbb95ffe7defbc/internal/server/evaluation/legacy_evaluator.go#L381-L387

**Comment by proxeter** [comment]
> One more place should be fixed as well
> 
> https://github.com/flipt-io/flipt/blob/504f8e0fbbff884c06ce1edbdfdbb95ffe7defbc/internal/server/evaluation/legacy_evaluator.go#L381-L387

@erka It's the same place as in PR. I can't understand what you mean
matchesString contains same check but has correct behaviour
https://github.com/flipt-io/flipt/blob/504f8e0fbbff884c06ce1edbdfdbb95ffe7defbc/internal/server/evaluation/legacy_evaluator.go#L346-L351

**Comment by erka** [comment]
@proxeter You're correct. My bad.

**Comment by markphelps** [comment]
I'll check the rust (client side eval) to see if it has the same bug

**Comment by markphelps** [comment]
Seems correct in the client-side eval code: 

https://github.com/flipt-io/flipt-client-sdks/blob/main/flipt-evaluation/src/lib.rs#L519-L520

https://github.com/flipt-io/flipt-client-sdks/blob/75a0bfd175da630664cb77bb9f6e8fe52d004ee8/flipt-evaluation/src/lib.rs#L567-L570

**Pull request merged**
