### PR TITLE
docs(examples): added example how to run flipt behind nginx

### PR DESCRIPTION
**Pull request by erka**
related #2723

### CODE REVIEW

**Comment by erka** [comment]
@GeorgeMac what do you think about this as a solution?

**Comment by martin-gft** [comment]
just gave this one a try and it works

**Comment by GeorgeMac** [comment]
That's amazing @erka 🙌 Great shout. Just get the ingress to do the rewrites, genius!

Maybe long term we can do something similar in Flipt too, but im glad if this unblocks you @martin-gft in the meantime?

**Comment by martin-gft** [comment]
@erka  @GeorgeMac  It does! Thank you both very much!

**Review by markphelps — APPROVED** [review]
nice one @erka !

**Pull request merged**
