### PR TITLE
Change test case to show the correct format of multi domains for CORS

### PR DESCRIPTION
**Pull request by showwin**
## Overview
The format of `cors.allowed_origins` config was changed by https://github.com/flipt-io/flipt/pull/1079 refactoring.
So I change the test case to explain the format explicitly.

## Explanation
Before the above change at v1.13.0, [the format with white space](https://github.com/flipt-io/flipt/commit/f06335ad5af6dd853b73b2126e550ae2b377424a#diff-6146da5455717d6d0dc2fcb1b31d8f88f3fb164a536d1bff64394511b2c0344a) worked fine since the parameter was parsed by `viper.GetStringSlice` [here](https://github.com/flipt-io/flipt/pull/1079/files#diff-9610c88fc96f562246494f72b1eaeff59e104154ccc636f919a8020506923d0fL22). But after the above change, it is parsed by `mapstructure.StringToSliceHookFunc(",")` [here](https://github.com/flipt-io/flipt/pull/1079/files#diff-54c7c1af5fa8d5db4dc49f0e8e80e93ba2b1183ba4d5c9e2e5729e6deae6a3cdR17) so the expected format was changed.
I'm not sure we should fix to parse for the previous format, but changing test case to show the correct format won't be harmful.

### CODE REVIEW

**Comment by GeorgeMac** [comment]
Thanks @showwin 🙏 This is definitely a regression! I think we could/should probably put things back.

As you pointed out, it is this mapstructure hook which does the splitting:
https://github.com/flipt-io/flipt/blob/b0b451ca8c9d93fde58b862b6582a49165330b9f/internal/config/config.go#L17

It appears that `viper.GetStringSlice` ultimately drops down to using:

https://github.com/spf13/cast/blob/2b0eb0f724e320b655240e331aef36d1175986c2/caste.go#L1276

Which is a call to `strings.Fields()` when moving the type from a string.

We could either:

(a) Switch to using `mapstructure.StringToSliceHookFunc(",")`?
(b) Copy the definition of the function in (a) and write an alternative to it which calls `strings.Fields()`?

e.g.
```go
// StringToSliceHookFunc returns a DecodeHookFunc that converts
// string to []string by splitting using strings.Fields().
func StringToSliceHookFunc() DecodeHookFunc {
	return func(
		f reflect.Kind,
		t reflect.Kind,
		data interface{}) (interface{}, error) {
		if f != reflect.String || t != reflect.Slice {
			return data, nil
		}

		raw := data.(string)
		if raw == "" {
			return []string{}, nil
		}

		return strings.Fields(raw), nil
	}
}
```

@markphelps any preferences? And shall we consider making this change and cutting it as a patch release?

It appears that the only `[]string` is the allowed origins. So, I think this is the only place in config affected.

Then we can adjust @showwin test contributed here to match the decision.

**Comment by markphelps** [comment]
@all-contributors please add @showwin for tests

**Comment by GeorgeMac** [comment]
I agree too. I think that would be the most prudent approach (b).

@showwin would you be interested in attempting this fix as part of this PR? No worries if not. I am happy to tackle it too.

**Review by markphelps — APPROVED** [review]

**Comment by showwin** [comment]
@GeorgeMac @markphelps Thank you guys for the good discussion!

@GeorgeMac 
>@showwin would you be interested in attempting this fix as part of this PR? No worries if not. I am happy to tackle it too.

TBH, I'm not good at writing Golang, so I appreciate it if you tackle this fix! Thank you 🙏

**Comment by GeorgeMac** [comment]
No worries @showwin, thanks again! I will get a PR up for that ASAP 👍

**Pull request merged**
