### PR TITLE
Onboarding page

### PR DESCRIPTION
**Pull request by markphelps**
Fixes: #2595 

Adding onboarding screen to help new users get going on first start

## Darkmode

https://github.com/flipt-io/flipt/assets/209477/32b12de0-fa08-4f9c-906c-2880a002d1d2

## Lightmode

https://github.com/flipt-io/flipt/assets/209477/4be19249-c93d-4443-ab18-0d8af5a9b74c

## TODO

- [ ] actually who on first run only, or if there is no data in db (no flags, etc)
- [x] test more in mobile
- [x] add onboarding section to either sidebar or support section so users can get back to it if they way
- [x] prob add some basic ui tests too

### CODE REVIEW

**Comment by markphelps** [comment]
I still need to figure out how to get it to show on first run by default. perhaps by redirecting the user there if they goto `/` (default) if there are no [`flags`, `segments`, `non-default namespaces`]?

**Comment by GeorgeMac** [comment]
That seems like a reasonable strategy @markphelps 
You can always navigate to /flags or /segments right, so it doesn't keep you from getting to the empty page if you so desire.
However, `/` just won't show `/flags` if theres no data, it will take you to onboarding.

> I still need to figure out how to get it to show on first run by default. perhaps by redirecting the user there if they goto `/` (default) if there are no [`flags`, `segments`, `non-default namespaces`]?

**Comment by markphelps** [comment]
cc @julesglad for any UI/UX advice / thoughts

**Comment by julesglad** [comment]
> cc @julesglad for any UI/UX advice / thoughts

@markphelps 

Hey, there. This is looking good. Just two things I thought I'd mention.

Upon hover, the icon is cut off halfway at the top of the tile. Might be best to push it up a little more so that it doesn't cut off awkwardly. This is purely visual and opinion. Just thought I'd mention it.

Also, on the dark mode, I think that some of the text (particularly the <p>{description}</p> could have more contrast to the black background. It can be a little hard to read, especially if someone is visually impaired.

**Comment by markphelps** [comment]
Thank you @julesglad ! I'll get those issues fixed up in another PR before release

**Pull request merged**
