### PR TITLE
refactor(storage): move s3fs to storage/fs/s3 and extract file types

### PR DESCRIPTION
**Pull request by erka**
Move s3fs to storage/fs/s3 and extract file types into storage/fs/blob package

This is related to work with Azure Blob Storage #2538

### CODE REVIEW

**Review by GeorgeMac — APPROVED** [review]
Nice tidy up!

**Comment by GeorgeMac** [comment]
Just fixing something I broke in CI so that the ITs run on this PR 👍

**Comment by erka** [comment]
@markphelps could you please  review/merge this?

**Review by markphelps — APPROVED** [review]
nice!

**Pull request merged**
