### PR TITLE
chore: pin redpanda images for integration testing

### PR DESCRIPTION
**Pull request by erka**

### CODE REVIEW

**Comment by markphelps** [comment]
@erka is this good to move out of draft? experiencing the same thing in #3326

**Comment by erka** [comment]
@markphelps actually it's the same as that pull requests. For some reason, if I create the PR from a fork it works fine but when it runs on upstream it fails. I see the difference with some dagger tasks but I have no clue why it makes the impact :(

**Comment by markphelps** [comment]
> @markphelps actually it's the same as that pull requests. For some reason, if I create the PR from a fork it works fine but when it runs on upstream it fails. I see the difference with some dagger tasks but I have no clue why it makes the impact :(
> 
> updated: I think it's related to `ERROR 2024-07-30 15:42:06,291 [shard 0:main] cluster - storage space alert: free space at 6.879% on /var/lib/redpanda/data: 72.505GiB total, 4.988GiB free, min. free 0.000bytes. Please adjust retention policies as needed to allow writing again`

likely related to the fact that we've used all our 'free' actions minutes for the month (which apparently doesn't reset until aug 22 😬 )

we are now on paid minutes though.. so i would assume it shouldn't block storage, maybe we need to upgrade to larger runners?

**Comment by markphelps** [comment]
> @markphelps actually it's the same as that pull requests. For some reason, if I create the PR from a fork it works fine but when it runs on upstream it fails. I see the difference with some dagger tasks but I have no clue why it makes the impact :(
> 
> updated: I think it's related to `ERROR 2024-07-30 15:42:06,291 [shard 0:main] cluster - storage space alert: free space at 6.879% on /var/lib/redpanda/data: 72.505GiB total, 4.988GiB free, min. free 0.000bytes. Please adjust retention policies as needed to allow writing again`

also where does the 80GB storage usage come from for redpanda?

**Comment by erka** [comment]
> also where does the 80GB storage usage come from for redpanda?

This is an interesting question. Maybe this is all space of the [runner](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#specifications-for-general-larger-runners).

**Pull request closed without merging**
