### PR TITLE
chore: Create SECURITY.md

### PR DESCRIPTION
**Pull request by markphelps**
Fixes: #2575

### CODE REVIEW

**Comment by erka** [comment]
One more thing to say about this. This could be placed in `.github` repo to apply to all company products.

**Comment by erka** [comment]
The repo also could include the  Code of conduct and other organization health files.

**Comment by markphelps** [comment]
Nice, will move to the org .github !

Also we have a CoC in the repo root

CleanShot 2023-12-21 at 17 09 36

**Comment by markphelps** [comment]
Added org wide: https://github.com/flipt-io/flipt/security/policy

Thanks for filing this @erka !!

**Pull request closed without merging**
