### PR TITLE
Add entityId to clickhouse analytics

### PR DESCRIPTION
**Pull request by tegorov**
When using percentage rollout, we need to know evaluation result by entityId.

### CODE REVIEW

**Comment by markphelps** [comment]
Thanks @tegorov ! Good idea. But we need to make this a new migration as we cant change existing ones since they would have already been applied for users who have run Flipt with Clickhouse integration.

Would you mind moving the change to be an `ALTER` in a new migration file like `config/migrations/clickhouse/1_add_entity_id.up.sql` or similar?

We use [golang-migrate](https://github.com/golang-migrate/migrate) under the hood which keeps track of applied migration versions

**Review by markphelps — CHANGES_REQUESTED** [review]
Thanks @tegorov ! Good idea. But we need to make this a new migration as we cant change existing ones since they would have already been applied for users who have run Flipt with Clickhouse integration.

Would you mind moving the change to be an ALTER in a new migration file like `config/migrations/clickhouse/1_add_entity_id.up.sql` or similar?

We use [golang-migrate](https://github.com/golang-migrate/migrate) under the hood which keeps track of applied migration versions

**Comment by tegorov** [comment]
@markphelps Thanks! 
Added a new migration file.

**Comment by markphelps** [comment]
@tegorov apologies, one last thing. We just changed our contribution policy to require sign off of a developer certificate (DCO) https://developercertificate.org/

would you mind following the steps here https://github.com/flipt-io/flipt/pull/2951/checks?check_run_id=23568365097 to sign the commit to get the check to pass?

**Comment by tegorov** [comment]
@markphelps done

**Comment by markphelps** [comment]
@all-contributors please add @tegorov for code

**Review by markphelps — APPROVED** [review]
looks great, thanks @tegorov !

**Pull request merged**
