### PR TITLE
fix(ui): assistance for arrays data in constraints

### LINKED ISSUE #2885: UI assistance for arrays data in constraints
### Problem

Currently the UI requires users to manually add raw json:
Screenshot 2024-03-21 at 10 29 07 PM

### Ideal Solution

Either add multiple options in the UI similar to segments:
Screenshot 2024-03-21 at 10 28 08 PM

Or input of raw text followed by a comma might be transformed into an array behind the scenes.
Screenshot 2024-03-21 at 10 35 22 PM

### Search

- [X] I searched for other open and closed issues before opening this

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by erka**
closes #2885

### CODE REVIEW

**Comment by erka** [comment]
@markphelps it isn't ready but I would like to get you feedback and thoughts.

**Comment by erka** [comment]
Screen Shot 2024-03-22 at 21 51 48

**Review by markphelps — COMMENTED** [review]
looks great so far @erka as usual!!  Thank you for taking this on!

I know you said it wasn't ready, but I tested it and works great for the most part. Just a couple minor things I noticed:

1.
CleanShot 2024-03-22 at 16 34 07@2x

we may want to make sure we strip certain characters like `[ ]` from the strings, as above caused an error:

CleanShot 2024-03-22 at 16 38 19

2. we probably want to truncate the values in the UI

CleanShot 2024-03-22 at 16 34 47@2x

3. we may want to play around with the colors a bit to try something lighter for the pills? wdyt?

**Comment by erka** [comment]
@markphelps I've addressed all of them except the first one. I don't see any issues with special characters, maybe `console.log` make you think it's broken.

**Review by markphelps — APPROVED** [review]
looks and works amazing @erka !!!

**Comment by markphelps** [comment]
I tested it for backward compatibility, from the current release of Flipt which only renders the raw array `['values', 'foo']` and it renders them correctly when built with this change

**Pull request merged**
