### PR TITLE
refactor(deps): replace yaml.v2 with yaml.v3

### PR DESCRIPTION
**Pull request by erka**

### CODE REVIEW

**Review by markphelps — APPROVED** [review]
👍🏻

**Comment by erka** [comment]
There is a small thing which breaks the tests. `yaml.v3` output  has different intent for list. 

The export output  with `yaml.v2` 

```yaml
version: "1.4"
namespace:
  key: default
  name: Default
  description: Default namespace
flags:
- key: a
  name: a
  type: BOOLEAN_FLAG_TYPE
  enabled: false
- key: b
  name: b
  type: VARIANT_FLAG_TYPE
  enabled: true
```

The export output with `yaml.v3`

```yaml
version: "1.4"
namespace:
  key: default
  name: Default
  description: Default namespace
flags:
  - key: a
    name: a
    type: BOOLEAN_FLAG_TYPE
    enabled: false
  - key: b
    name: b
    type: VARIANT_FLAG_TYPE
    enabled: true
```

Is this a breaking change @markphelps @GeorgeMac ?

**Comment by markphelps** [comment]
No I don't think it's a breaking change as long as it can still read the previous version

**Comment by erka** [comment]
I am closing this for now. There are too many changes in the test data and there is no way to configure the output to be the same as yaml.v2.

**Pull request closed without merging**
