### PR TITLE
feat(ui/tokens): delete multiple tokens

### PR DESCRIPTION
**Pull request by erka**
Refs: #2275, FLI-215

### CODE REVIEW

**Comment by erka** [comment]
@markphelps please take a look and provide feedback.

The delete button is too big as the replacement of 'Name'.  Any workaround for it?
The delete token modal probably should better formatting for multiple tokens. Any suggestions?
Anything else?

**Comment by markphelps** [comment]
@erka this looks great! I responded to most the questions in the PR on your PR https://github.com/erka/flipt/pull/1

I think its ok that the Delete button hides the name field on the table

Really appreciate this!! Works great!

**Comment by erka** [comment]
There is some side effect which happens right now. After deletions the tokens if you create the new one it will be selected for deletion. I believe the `rowSelection` state isn't cleanup up after the api calls. If the `rowSelection` will be move to the `Tokens.tsx` but then you need `RowSelectionState` there which looks bad.

By the way there is one strange state with filter too in `main` branch. If you use filter to find one token and delete it you will see a blank table and no filter input... It looks like as a bug.

**Comment by markphelps** [comment]
@erka what do you think about https://github.com/erka/flipt/pull/2 , which passes down the existing `tokensVersion` prop to then reset selected rows if the underlying tokens change (such as delete)?

I think it might be nicer than using events?

> By the way there is one strange state with filter too in main branch. If you use filter to find one token and delete it you will see a blank table and no filter input... It looks like as a bug.

Yes ☝🏻 def sounds like a bug. We should file and fix that. I'm happy to file it in the morning (US) or if you are able to first, either way.

Thank you again for this contribution!!

**Review by markphelps — APPROVED** [review]
thank you for the contribution @erka !! Looks great and very much appreciated!

**Comment by markphelps** [comment]
@all-contributors please add @erka for code

**Pull request merged**
