### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by byronrwalker**
Typo fix: "Use cases"

### CODE REVIEW

**Comment by byronrwalker** [comment]
cc: @markphelps

**Review by markphelps — APPROVED** [review]
Oh hi Byron! Thank you. 😊

**Comment by erka** [comment]
Hey @byronrwalker @markphelps. What is the best way to resolve DCO here?

**Comment by markphelps** [comment]
@erka I just marked it as skipped since its a README update and not actual running code.

**Pull request merged**
