### PR TITLE
fix: check authz for evaluation endpoints

### PR DESCRIPTION
**Pull request by markphelps**
Reported in Discord: https://discord.com/channels/960634591000014878/1281742374275649569

A user reported that with authz enabled evaluation for client side SDKs did not work. This fixes that and adds more testing

Also disables authz checking for ofrep server endpoints

### CODE REVIEW

**Review by GeorgeMac — CHANGES_REQUESTED** [review]
I think we need to update the authz engine to support requesting at least read flag in the requested namespace here. Or go as far as the authz engine supporting request more than one resource to do flag and segment.
by blanket disabling it you let anyone with authn but no authz read from any namespace.

**Comment by GeorgeMac** [comment]
I made a PR on this PR ☝️

**Comment by erka** [comment]
@markphelps is it any reason why ofrep and evaluation endpoints should not have authz?

**Comment by markphelps** [comment]
> @markphelps is it any reason why ofrep and evaluation endpoints should not have authz?

I guess I could undo that change for now? although we skipped evaluation server-side authz on purpose it seems when we initially implemented it. I think it gets harder for bulk eval as idk if we wanna check each flag?

**Comment by erka** [comment]
>  as idk if we wanna check each flag?

What is it? I don't see any restrictions for a specific flag during CRUD.  

We could have another action like `evaluate` for `flag` or `namespace` resource. It may be helpful for those who uses one Flipt instance for different environments with different namespaces.

**Comment by GeorgeMac** [comment]
> We could have another action like evaluate for flag or namespace resource. It may be helpful for those who use one Flipt instance for different environments with different namespaces.

My gut leans on adding a new action / verb as @erka suggests here, specifically for evaluations (eval + ofrep, but not necessarily data).
Long term, I think a specific verb/action makes sense. It makes it clearer what the intent is and allows e.g. audit log consumers to ignore evaluations (if they wish), which might be high-volume output. Adding in read flag and segment on evaluation kind of bulks up the audit log stream potentially quite a bit.

I think maybe read flag / segment might still make sense for the eval snapshot data endpoint though.
The caller is not specifically evaluating, they're reading all flags and segments in a namespace.
Since it is designed to be fetched less frequently that actual evaluations, it doesn't have the same impact on audit log volume. So less concerned about that in this instance.

**Comment by erka** [comment]
@markphelps  @GeorgeMac Let's move this discussion to another issue or PR. I believe it's the best to resolve the original issue right now.

**Comment by markphelps** [comment]
@erka @GeorgeMac are we good to merge this to unblock the user in Discord? I agree we should prob discuss evaluation server side authz in another issue

**Review by GeorgeMac — APPROVED** [review]
Yes @markphelps 👍

**Pull request merged**
