### PR TITLE
chore: refactor cache to rm from middleware and use storage layer

### PR DESCRIPTION
**Pull request by markphelps**
Re: #3158

Go back(?) to caching only in storage layer as middleware is full of potential footguns

I feel like I've made this change 3 times by now..

### CODE REVIEW

**Comment by markphelps** [comment]
Ready for first pass. I will work on benchmarking this change against the current 'live' caching in middleware

**Review by GeorgeMac — COMMENTED** [review]
I think the PR looks great. My one question is do we want to add distributions caching?But I think that can come after you've benchmarked, if the performance isn't satisfactory enough.

**Comment by markphelps** [comment]
Benchmarks of THIS PR:

## GetFlag (no-cache / cache)

flag-no-cache
flag-cache

## Evaluate Variant (no-cache / cache)

variant-no-cache
variant-cache

## Evaluate Boolean (no-cache / cache)

boolean-no-cache
boolean-cache

**Review by GeorgeMac — APPROVED** [review]
⚡

**Comment by markphelps** [comment]
Currently comparing this PR with `latest` Flipt release (which has middleware caching), will update with those results in a few

**Comment by markphelps** [comment]
Using `latest` Flipt Docker image:

## Get Flag (no-cache/cache)

flag-latest-no-cache
flag-latest-cache

## Evaluate Variant (no-cache/cache)

variant-latest-no-cache
variant-latest-cache

## Evaluate Boolean (no-cache/cache)

boolean-latest-no-cache
boolean-latest-cache


will create summary table next

**Comment by markphelps** [comment]
## Storage Layer Cache Benchmarks (this pr)

| Request           | Mean       | 95th Percentile | 99th Percentile | Max         |
|-------------------|------------|-----------------|-----------------|-------------|
| boolean-cache     | 1.748039ms | 4.365747ms      | 12.940643ms     | 78.970371ms |
| boolean-no-cache  | 2.073881ms | 2.596417ms      | 14.441149ms     | 159.673178ms|
| variant-cache     | 1.728889ms | 4.08327ms       | 9.163761ms      | 43.351857ms |
| variant-no-cache  | 5.224469ms | 6.262917ms      | 22.578791ms     | 283.471747ms|
| flag-cache        | 1.490036ms | 3.901015ms      | 7.629809ms      | 43.772426ms |
| flag-no-cache     | 1.632326ms | 4.044873ms      | 8.100693ms      | 40.17379ms  |

## Middleware Layer Cache (current release)

| Request   | Mean       | 95th Percentile | 99th Percentile | Max         |
|-----------|------------|-----------------|-----------------|-------------|
| boolean-cache  | 1.819804ms | 3.033069ms      | 8.118996ms      | 147.070874ms |
| boolean-no-cache  | 1.732341ms | 2.670454ms      | 6.462124ms      | 146.375622ms |
| variant-cache   | 1.792146ms | 2.363489ms      | 5.907704ms      | 127.101229ms |
| variant-no-cache  | 2.010389ms | 2.687258ms      | 4.85096ms       | 101.35828ms |
| flag-cache   | 1.499888ms | 3.813006ms      | 7.899383ms      | 32.149513ms |
| flag-no-cache  | 2.03005ms  | 3.782634ms      | 12.547705ms     | 150.098193ms |

**Comment by markphelps** [comment]
Chat GPT analysis:

### Summary

#### **1. Storage Layer Cache Benchmarks (this PR)**

**Overall Analysis:**
- Mean and 95th percentile times are generally lower, indicating more consistent and slightly better performance in most cases compared to the middleware layer.
- Maximum times show significant spikes in `boolean-no-cache` and `variant-no-cache` cases.

**Performance Data:**

| Request           | Mean       | 95th Percentile | 99th Percentile | Max         |
|-------------------|------------|-----------------|-----------------|-------------|
| boolean-cache     | 1.748039ms | 4.365747ms      | 12.940643ms     | 78.970371ms |
| boolean-no-cache  | 2.073881ms | 2.596417ms      | 14.441149ms     | 159.673178ms|
| variant-cache     | 1.728889ms | 4.08327ms       | 9.163761ms      | 43.351857ms |
| variant-no-cache  | 5.224469ms | 6.262917ms      | 22.578791ms     | 283.471747ms|
| flag-cache        | 1.490036ms | 3.901015ms      | 7.629809ms      | 43.772426ms |
| flag-no-cache     | 1.632326ms | 4.044873ms      | 8.100693ms      | 40.17379ms  |

#### **2. Middleware Layer Cache Benchmarks (current release)**

**Overall Analysis:**
- Mean times are slightly higher across most requests compared to the storage layer.
- Maximum times are significantly lower in the `variant-no-cache` case but higher in others, indicating more predictable performance but slightly worse in some cases.

**Performance Data:**

| Request           | Mean       | 95th Percentile | 99th Percentile | Max         |
|-------------------|------------|-----------------|-----------------|-------------|
| boolean-cache     | 1.819804ms | 3.033069ms      | 8.118996ms      | 147.070874ms|
| boolean-no-cache  | 1.732341ms | 2.670454ms      | 6.462124ms      | 146.375622ms|
| variant-cache     | 1.792146ms | 2.363489ms      | 5.907704ms      | 127.101229ms|
| variant-no-cache  | 2.010389ms | 2.687258ms      | 4.85096ms       | 101.35828ms |
| flag-cache        | 1.499888ms | 3.813006ms      | 7.899383ms      | 32.149513ms |
| flag-no-cache     | 2.03005ms  | 3.782634ms      | 12.547705ms     | 150.098193ms|

### Key Points:
1. **Performance Consistency:**
   - The storage layer shows better mean and 95th percentile times, indicating more consistent performance in most scenarios.
   - The middleware layer shows less variation in max times, especially in the `variant-no-cache` case.

2. **Outliers and Maximum Times:**
   - The storage layer has significantly higher max times for `boolean-no-cache` and `variant-no-cache`, suggesting potential performance spikes under certain conditions.
   - Middleware layer has generally higher max times in `boolean-cache` and `flag-no-cache`.

3. **Mean Performance:**
   - Mean performance is slightly better in the storage layer across most cases, suggesting it handles typical load more efficiently.
   
4. **Cache Impact:**
   - Caching shows improvements in both layers, but the storage layer's caching seems to provide slightly better performance improvements, especially under typical conditions (mean and 95th percentile).

In conclusion, the storage layer cache generally provides more consistent and slightly better performance under typical conditions, but with potential for significant performance spikes in some scenarios. The middleware layer cache provides more predictable performance without severe outliers but is slightly less efficient under typical conditions.

**Comment by markphelps** [comment]
Note: all benchmarks were done via Dagger on my local machine, with Flipt configured using Postgres backing storage and Redis for cache

**Pull request merged**
