### PR TITLE
feat(ui): save sort state in redux

### PR DESCRIPTION
**Pull request by markphelps**
Re: #3413 

Moves sorting state of tables to redux so that it persists between pages

## TODO

- [x] Segments Table
- [ ] ~~Anywhere else we allow sorting in tables~~ will do this if requested by users later

### CODE REVIEW

**Comment by erka** [comment]
We need to change API to pass the order param because of pagination.

**Comment by markphelps** [comment]
> We need to change API to pass the order param because of pagination.

How do you mean? The pagination still happens client side as well

**Comment by erka** [comment]
Client fetches the limited number of flags/segments, right? If backend has no knowledge of ordering that may lead to unexpected results if I don't miss something.

**Comment by erka** [comment]
> Client fetches the limited number of flags/segments, right? If backend has no knowledge of ordering that may lead to unexpected results if I don't miss something.

My bad... it looks like client fetches all the flags at once. I looked at tests where limit is set

**Comment by markphelps** [comment]
Yeah we would eventually like to move pagination/sorting/etc to server side (call the API) but this has implications with the search box that pops up if you have more than 15 flags (I think).

Currently search is done client side too, which it can do because it pulls down all flags at once. If we moved to server side pagination we would have to come up with a different solution for search, like an API endpoint

**Review by erka — APPROVED** [review]
nice

**Pull request merged**
