### PR TITLE
fix(ui): Button color switch for enabled and hover

### PR DESCRIPTION
**Pull request by julesglad**
Fixes: #2544

### CODE REVIEW

**Comment by markphelps** [comment]
Thanks @julesglad !! Would you say this fully fixes #2544 ?

**Comment by markphelps** [comment]
@all-contributors please add @julesglad for code

**Review by markphelps — APPROVED** [review]
lgtm!! thanks!!

**Comment by julesglad** [comment]
> Thanks @julesglad !! Would you say this fully fixes #2544 ?

Yes, it does!

**Pull request merged**
